// <auto-generated />
using System;
using AgroVision.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace AgroVision.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AgroVisionContext))]
    partial class AgroVisionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgroVision.Domain.Entities.AnaliseDrone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ANALISE_DRONE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AreaAfetadaPercentual")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("AREA_AFETADA_PERCENTUAL");

                    b.Property<DateTime>("DataAnalise")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ANALISE");

                    b.Property<decimal>("IndiceSaude")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("INDICE_SAUDE");

                    b.Property<decimal>("IndiceVegetacaoNdvi")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("INDICE_VEGETACAO_NDVI");

                    b.Property<int?>("MissaoDroneId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MISSAO_DRONE");

                    b.Property<string>("NivelRisco")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NIVEL_RISCO");

                    b.Property<string>("ObservacaoImagem")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("OBSERVACAO_IMAGEM");

                    b.Property<int>("PlantacaoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PLANTACAO");

                    b.Property<bool>("PragasDetectadas")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("PRAGAS_DETECTADAS");

                    b.Property<string>("Recomendacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("RECOMENDACAO");

                    b.Property<string>("StatusAnalise")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS_ANALISE");

                    b.Property<decimal>("TemperaturaMedia")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("TEMPERATURA_MEDIA");

                    b.Property<decimal>("UmidadeSolo")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("UMIDADE_SOLO");

                    b.HasKey("Id");

                    b.HasIndex("MissaoDroneId")
                        .IsUnique()
                        .HasFilter("\"ID_MISSAO_DRONE\" IS NOT NULL");

                    b.HasIndex("PlantacaoId");

                    b.ToTable("TB_ANALISE_DRONE_GS", (string)null);
                });

            modelBuilder.Entity("AgroVision.Domain.Entities.Drone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DRONE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ATIVO");

                    b.Property<decimal>("AutonomiaMinutos")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("AUTONOMIA_MINUTOS");

                    b.Property<string>("CodigoIdentificacao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)")
                        .HasColumnName("CODIGO_IDENTIFICACAO");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)")
                        .HasColumnName("FABRICANTE");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)")
                        .HasColumnName("MODELO");

                    b.HasKey("Id");

                    b.HasIndex("CodigoIdentificacao")
                        .IsUnique();

                    b.ToTable("TB_DRONE_GS", (string)null);
                });

            modelBuilder.Entity("AgroVision.Domain.Entities.Insumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_INSUMO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataUltimaAplicacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ULTIMA_APLICACAO");

                    b.Property<decimal>("EstoqueMinimo")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("ESTOQUE_MINIMO");

                    b.Property<string>("NomeInsumo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NOME_INSUMO");

                    b.Property<int>("PlantacaoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PLANTACAO");

                    b.Property<decimal>("QuantidadeEstoque")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("QTD_ESTOQUE");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("UNIDADE_MEDIDA");

                    b.HasKey("Id");

                    b.HasIndex("PlantacaoId");

                    b.ToTable("TB_INSUMO_GS", (string)null);
                });

            modelBuilder.Entity("AgroVision.Domain.Entities.LeituraSensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LEITURA_SENSOR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataLeitura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_LEITURA");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("NUMBER(10,6)")
                        .HasColumnName("LATITUDE");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("NUMBER(10,6)")
                        .HasColumnName("LONGITUDE");

                    b.Property<int>("MissaoDroneId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MISSAO_DRONE");

                    b.Property<string>("TipoSensor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("TIPO_SENSOR");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("UNIDADE_MEDIDA");

                    b.Property<decimal>("Valor")
                        .HasColumnType("NUMBER(15,4)")
                        .HasColumnName("VALOR");

                    b.HasKey("Id");

                    b.HasIndex("MissaoDroneId");

                    b.ToTable("TB_LEITURA_SENSOR_GS", (string)null);
                });

            modelBuilder.Entity("AgroVision.Domain.Entities.LogErro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LOG");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoErro")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODIGO_ERRO");

                    b.Property<DateTime>("DataErro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ERRO");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("MENSAGEM_ERRO");

                    b.Property<string>("NomeProcedure")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME_PROCEDURE");

                    b.Property<string>("NomeUsuario")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NOME_USER_GS");

                    b.HasKey("Id");

                    b.ToTable("TB_LOG_ERRO_GS", (string)null);
                });

            modelBuilder.Entity("AgroVision.Domain.Entities.MissaoDrone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MISSAO_DRONE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AltitudeMedia")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("ALTITUDE_MEDIA");

                    b.Property<decimal>("AreaMapeada")
                        .HasColumnType("NUMBER(15,2)")
                        .HasColumnName("AREA_MAPEADA");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_FIM");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_INICIO");

                    b.Property<int>("DroneId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DRONE");

                    b.Property<int>("PlantacaoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PLANTACAO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS_MISSAO");

                    b.HasKey("Id");

                    b.HasIndex("DroneId");

                    b.HasIndex("PlantacaoId");

                    b.ToTable("TB_MISSAO_DRONE_GS", (string)null);
                });

            modelBuilder.Entity("AgroVision.Domain.Entities.OcorrenciaPlantacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_OCORRENCIA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnaliseDroneId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ANALISE_DRONE");

                    b.Property<DateTime>("DataOcorrencia")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_OCORRENCIA");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("NivelRisco")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NIVEL_RISCO");

                    b.Property<int>("PlantacaoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PLANTACAO");

                    b.Property<bool>("Resolvida")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("RESOLVIDA");

                    b.Property<string>("TipoOcorrencia")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)")
                        .HasColumnName("TIPO_OCORRENCIA");

                    b.HasKey("Id");

                    b.HasIndex("AnaliseDroneId");

                    b.HasIndex("PlantacaoId");

                    b.ToTable("TB_OCORRENCIA_PLANTACAO_GS", (string)null);
                });

            modelBuilder.Entity("AgroVision.Domain.Entities.Plantacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PLANTACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AreaPlantio")
                        .HasColumnType("NUMBER(15,2)")
                        .HasColumnName("AREA_PLANTIO");

                    b.Property<bool>("Ativa")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ATIVA");

                    b.Property<string>("Cultura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CULTURA");

                    b.Property<DateTime>("DataPlantio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_PLANTIO");

                    b.Property<string>("LocalPlantio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("LOCAL_PLANTIO");

                    b.Property<decimal>("ProdutividadeEstimada")
                        .HasColumnType("NUMBER(15,2)")
                        .HasColumnName("PRODUTIVIDADE_ESTIMADA");

                    b.Property<string>("StatusPlantio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS_PLANTIO");

                    b.Property<string>("TipoPlantio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TIPO_PLANTIO");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_PLANTACOES_GS", (string)null);
                });

            modelBuilder.Entity("AgroVision.Domain.Entities.RecomendacaoAgronomica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_RECOMENDACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnaliseDroneId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ANALISE_DRONE");

                    b.Property<bool>("Concluida")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("CONCLUIDA");

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_GERACAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("PRIORIDADE");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TITULO");

                    b.HasKey("Id");

                    b.HasIndex("AnaliseDroneId");

                    b.ToTable("TB_RECOMENDACAO_AGRONOMICA_GS", (string)null);
                });

            modelBuilder.Entity("AgroVision.Domain.Entities.Safra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SAFRA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataColheita")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_COLHEITA");

                    b.Property<decimal>("PerdaEstimada")
                        .HasColumnType("NUMBER(15,2)")
                        .HasColumnName("PERDA_ESTIMADA");

                    b.Property<int>("PlantacaoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PLANTACAO");

                    b.Property<decimal>("QuantidadeColhida")
                        .HasColumnType("NUMBER(15,2)")
                        .HasColumnName("QTD_COLHIDA");

                    b.Property<decimal>("ReceitaEstimada")
                        .HasColumnType("NUMBER(15,2)")
                        .HasColumnName("RECEITA_ESTIMADA");

                    b.HasKey("Id");

                    b.HasIndex("PlantacaoId");

                    b.ToTable("TB_SAFRA_GS", (string)null);
                });

            modelBuilder.Entity("AgroVision.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USER");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("Cpf")
                        .HasColumnType("NUMBER(11)")
                        .HasColumnName("CPF_USER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)")
                        .HasColumnName("NOME_USER");

                    b.Property<string>("NomeFazenda")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)")
                        .HasColumnName("NM_FAZENDA");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("NVARCHAR2(18)")
                        .HasColumnName("SENHA_USER");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("TB_USER_GS", (string)null);
                });

            modelBuilder.Entity("AgroVision.Domain.Entities.AnaliseDrone", b =>
                {
                    b.HasOne("AgroVision.Domain.Entities.MissaoDrone", "MissaoDrone")
                        .WithOne()
                        .HasForeignKey("AgroVision.Domain.Entities.AnaliseDrone", "MissaoDroneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgroVision.Domain.Entities.Plantacao", "Plantacao")
                        .WithMany("AnalisesDrone")
                        .HasForeignKey("PlantacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MissaoDrone");

                    b.Navigation("Plantacao");
                });

            modelBuilder.Entity("AgroVision.Domain.Entities.Insumo", b =>
                {
                    b.HasOne("AgroVision.Domain.Entities.Plantacao", "Plantacao")
                        .WithMany("Insumos")
                        .HasForeignKey("PlantacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plantacao");
                });

            modelBuilder.Entity("AgroVision.Domain.Entities.LeituraSensor", b =>
                {
                    b.HasOne("AgroVision.Domain.Entities.MissaoDrone", "MissaoDrone")
                        .WithMany("LeiturasSensor")
                        .HasForeignKey("MissaoDroneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MissaoDrone");
                });

            modelBuilder.Entity("AgroVision.Domain.Entities.MissaoDrone", b =>
                {
                    b.HasOne("AgroVision.Domain.Entities.Drone", "Drone")
                        .WithMany("Missoes")
                        .HasForeignKey("DroneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgroVision.Domain.Entities.Plantacao", "Plantacao")
                        .WithMany("MissoesDrone")
                        .HasForeignKey("PlantacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drone");

                    b.Navigation("Plantacao");
                });

            modelBuilder.Entity("AgroVision.Domain.Entities.OcorrenciaPlantacao", b =>
                {
                    b.HasOne("AgroVision.Domain.Entities.AnaliseDrone", "AnaliseDrone")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("AnaliseDroneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgroVision.Domain.Entities.Plantacao", "Plantacao")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("PlantacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnaliseDrone");

                    b.Navigation("Plantacao");
                });

            modelBuilder.Entity("AgroVision.Domain.Entities.Plantacao", b =>
                {
                    b.HasOne("AgroVision.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Plantacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AgroVision.Domain.Entities.RecomendacaoAgronomica", b =>
                {
                    b.HasOne("AgroVision.Domain.Entities.AnaliseDrone", "AnaliseDrone")
                        .WithMany("Recomendacoes")
                        .HasForeignKey("AnaliseDroneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnaliseDrone");
                });

            modelBuilder.Entity("AgroVision.Domain.Entities.Safra", b =>
                {
                    b.HasOne("AgroVision.Domain.Entities.Plantacao", "Plantacao")
                        .WithMany("Safras")
                        .HasForeignKey("PlantacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plantacao");
                });

            modelBuilder.Entity("AgroVision.Domain.Entities.AnaliseDrone", b =>
                {
                    b.Navigation("Ocorrencias");

                    b.Navigation("Recomendacoes");
                });

            modelBuilder.Entity("AgroVision.Domain.Entities.Drone", b =>
                {
                    b.Navigation("Missoes");
                });

            modelBuilder.Entity("AgroVision.Domain.Entities.MissaoDrone", b =>
                {
                    b.Navigation("LeiturasSensor");
                });

            modelBuilder.Entity("AgroVision.Domain.Entities.Plantacao", b =>
                {
                    b.Navigation("AnalisesDrone");

                    b.Navigation("Insumos");

                    b.Navigation("MissoesDrone");

                    b.Navigation("Ocorrencias");

                    b.Navigation("Safras");
                });

            modelBuilder.Entity("AgroVision.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Plantacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
